apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: media
data:
  CREATE_TUN_DEVICE: "False"
  GLOBAL_APPLY_PERMISSIONS: "False"
  LOCAL_NETWORK: 10.10.0.0/26
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: PIA
  PIA_PROTOCOL: TCP
  PIA_COUNTRY: "DE"
  PIA_CATEGORY: "P2P"
  LOG_TO_STDOUT: "true"
  PUID: "1000"
  PGID: "1000"
  TRANSMISSION_ALT_SPEED_ENABLED: "true"
  TRANSMISSION_ALT_SPEED_DOWN: "10000"
  TRANSMISSION_ALT_SPEED_UP: "5000"
  TRANSMISSION_UMASK: "002"
  TRANSMISSION_HOME: "/config/transmission-home"
  TRANSMISSION_DOWNLOAD_DIR: "/data/downloads"
  TRANSMISSION_INCOMPLETE_DIR: "/data/incomplete"
  TRANSMISSION_WATCH_DIR: "/data/watch"
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "4"
  TRANSMISSION_PEER_PORT: "47444"
  TRANSMISSION_RATIO_LIMIT: "1"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "5000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "1000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  TRANSMISSION_MAX_PEERS_GLOBAL: "400"
  TRANSMISSION_MAX_PEERS_PER_TORRENT: "200"
  TRANSMISSION_DEBUG: "true"
  TRANSMISSION_BLOCKLIST_ENABLED: "true"
  TRANSMISSION_BLOCKLIST_URL: "https://raw.githubusercontent.com/Naunter/BT_BlockLists/master/bt_blocklists.gz"
  WEBPROXY_ENABLED: "false"
  HEALTH_CHECK_HOST: "google.co.uk"